# Generated by Django 5.0 on 2024-10-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('INACTIVE', 'Inactive'), ('ACTIVE', 'Active')], default='INACTIVE', max_length=10)),
                ('discount', models.IntegerField(default=0)),
                ('purchased', models.IntegerField(default=0)),
                ('product_img', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
