# Generated by Django 5.1.2 on 2024-11-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_full_description_product_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
